### Global params
game: Connect4
random_seed: 33
steps: 2500
checkpoint_freq: 200

### MCTS params
n_simulations: 100
C_puct: 1.0
dirichlet_alpha: 0.75

### Training params
batch_size: 256
memory_capacity: 5000
lr: .2  # 
lr_gamma: 0.1
lr_step_size: 2500 
lr_scheduler_last_step: 10000
momentum: 0.9
weight_decay: 0.0001