# initial_config
random_seed: 3
epochs: 100
iters: 2500  # minibatches per epoch
learning_steps: 1000


Trainer:
  batch_size: 64
  lr: .2 
  # lr_gamma: .9
  # lr_step_size: 5 # how often (epochs) to decrease lr 
  momentum: 0.9 # ?
  