### Global params
game: Connect4
random_seed: 3
steps: 50
checkpoint_freq: 10

### MCTS params
n_simulations: 2
C_puct: 2.0
dirichlet_alpha: 0.75

### Eval params
eval: True
eval_sims: 2
eval_episodes: 10


### Training params
batch_size: 10
memory_capacity: 1000
# start_memory_cap: 1000
# end_memory_cap: 2000
memory_step: 4000
lr: .2
lr_gamma: 0.1
lr_step_size: 4000
lr_scheduler_last_step: 16000
momentum: 0.9
weight_decay: 0.0001
horizontal_flip: True